### ISSUE TITLE
Publish on non-existent topic causes server to panic

### ISSUE THREAD

**Issue by shivasishdas** [razorpay/metro#115]
```
{"level":"info","ts":1620324655.1963735,"caller":"web/publisherserver.go:28","msg":"produce request received","appEnv":"","serviceName":"metro","gitCommitHash":"9d13d67f1ae219eca7e9bd4b52722b56279819ba","method":"/google.pubsub.v1.Publisher/Publish","peer.address":"127.0.0.1:53090","grpc.request.rzp.id":"50743b4b-4728-420e-826e-52b6aa9cb17c","req":"projects/perf10/topics/perftopic17"}
{"level":"info","ts":1620324655.1967297,"caller":"messagebroker/kafka.go:100","msg":"kafka producer: initializing new","appEnv":"","serviceName":"metro","gitCommitHash":"9d13d67f1ae219eca7e9bd4b52722b56279819ba","method":"/google.pubsub.v1.Publisher/Publish","peer.address":"127.0.0.1:53090","grpc.request.rzp.id":"50743b4b-4728-420e-826e-52b6aa9cb17c","options":{"Topic":"projects/perf10/topics/perftopic17","Partition":0,"TimeoutMs":500}}
{"level":"info","ts":1620324655.2207124,"caller":"messagebroker/kafka.go:123","msg":"kafka producer: initialized","appEnv":"","serviceName":"metro","gitCommitHash":"9d13d67f1ae219eca7e9bd4b52722b56279819ba","method":"/google.pubsub.v1.Publisher/Publish","peer.address":"127.0.0.1:53090","grpc.request.rzp.id":"50743b4b-4728-420e-826e-52b6aa9cb17c"}
{"level":"info","ts":1620324655.22208,"caller":"messagebroker/kafka.go:339","msg":"normalized topic name","appEnv":"","serviceName":"metro","gitCommitHash":"9d13d67f1ae219eca7e9bd4b52722b56279819ba","method":"/google.pubsub.v1.Publisher/Publish","peer.address":"127.0.0.1:53090","grpc.request.rzp.id":"50743b4b-4728-420e-826e-52b6aa9cb17c","topic":"projects_perf10_topics_perftopic17"}
{"level":"error","ts":1620324685.2515993,"caller":"messagebroker/kafka.go:366","msg":"kafka: error in publishing messages","appEnv":"","serviceName":"metro","gitCommitHash":"9d13d67f1ae219eca7e9bd4b52722b56279819ba","method":"/google.pubsub.v1.Publisher/Publish","peer.address":"127.0.0.1:53090","grpc.request.rzp.id":"50743b4b-4728-420e-826e-52b6aa9cb17c","error":"Broker: Unknown topic or partition","stacktrace":"github.com/razorpay/metro/pkg/messagebroker.(*KafkaBroker).SendMessage\n\t/src/pkg/messagebroker/kafka.go:366\ngithub.com/razorpay/metro/internal/publisher.(*Core).Publish\n\t/src/internal/publisher/core.go:46\ngithub.com/razorpay/metro/service/web.publisherServer.Publish\n\t/src/service/web/publisherserver.go:29\ngithub.com/razorpay/metro/rpc/proto/v1._Publisher_Publish_Handler.func1\n\t/src/rpc/proto/v1/spec_grpc.pb.go:342\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1\n\t/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:31\ngithub.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1\n\t/src/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:107\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1\n\t/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34\ngithub.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1\n\t/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing/server_interceptors.go:30\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1\n\t/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34\ngithub.com/razorpay/metro/internal/interceptors.UnaryServerLoggerInterceptor.func1\n\t/src/internal/interceptors/logger.go:17\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1\n\t/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34\ngithub.com/razorpay/metro/internal/interceptors.UnaryServerTagInterceptor.func1\n\t/src/internal/interceptors/tags.go:33\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1\n\t/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34\ngithub.com/grpc-ecosystem/go-grpc-middleware/tags.UnaryServerInterceptor.func1\n\t/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/tags/interceptors.go:21\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1\n\t/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:39\ngithub.com/razorpay/metro/rpc/proto/v1._Publisher_Publish_Handler\n\t/src/rpc/proto/v1/spec_grpc.pb.go:344\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/src/vendor/google.golang.org/grpc/server.go:1217\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/src/vendor/google.golang.org/grpc/server.go:1540\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/src/vendor/google.golang.org/grpc/server.go:878"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xdf19c1]

goroutine 216 [running]:
github.com/razorpay/metro/pkg/messagebroker.(*KafkaBroker).SendMessage(0xc000392050, 0x18035a0, 0xc000448ea0, 0xc0003a6480, 0x22, 0x20165e8, 0x0, 0x0, 0x0, 0x0, ...)
	/src/pkg/messagebroker/kafka.go:367 +0xc21
github.com/razorpay/metro/internal/publisher.(*Core).Publish(0xc0000a0360, 0x18035a0, 0xc000448ea0, 0xc00014d400, 0x0, 0x0, 0x0, 0xc00024b4c0, 0x2)
	/src/internal/publisher/core.go:46 +0x2d5
github.com/razorpay/metro/service/web.publisherServer.Publish(0x18037e0, 0xc00005c280, 0x180ea40, 0xc0000d49f0, 0x17e5960, 0xc0000a0360, 0x18035a0, 0xc000448ea0, 0xc00014d400, 0x180a9c0, ...)
	/src/service/web/publisherserver.go:29 +0x151
github.com/razorpay/metro/rpc/proto/v1._Publisher_Publish_Handler.func1(0x18035a0, 0xc000448ea0, 0x14bf7a0, 0xc00014d400, 0xe62f44, 0xc0000b72c0, 0xc000448f00, 0x3)
	/src/rpc/proto/v1/spec_grpc.pb.go:342 +0x89
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x18035a0, 0xc000448ea0, 0x14bf7a0, 0xc00014d400, 0x23, 0xc00014d4a0, 0xc000448e70, 0x1418580)
	/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:31 +0x114
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x18035a0, 0xc000448ea0, 0x14bf7a0, 0xc00014d400, 0xc0005dd440, 0xc00014d450, 0x0, 0xc0005dd5c0, 0x475b10, 0x0)
	/src/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:107 +0xad
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x18035a0, 0xc000448ea0, 0x14bf7a0, 0xc00014d400, 0x15a5e89, 0x23, 0x18035a0, 0xc000448ea0)
	/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x9c
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0x18035a0, 0xc000448e70, 0x14bf7a0, 0xc00014d400, 0xc0005dd440, 0xc00014d450, 0x509946, 0x14dfec0, 0xc000448e70, 0x13b3520)
	/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing/server_interceptors.go:30 +0xda
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x18035a0, 0xc000448e70, 0x14bf7a0, 0xc00014d400, 0x155b3a0, 0xc000134070, 0x18035a0, 0xc000448e70)
	/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x9c
github.com/razorpay/metro/internal/interceptors.UnaryServerLoggerInterceptor.func1(0x18035a0, 0xc000448de0, 0x14bf7a0, 0xc00014d400, 0xc0005dd440, 0xc00014d450, 0x140d5a0, 0xc000448db0, 0x158438c, 0x6)
	/src/internal/interceptors/logger.go:17 +0x190
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x18035a0, 0xc000448de0, 0x14bf7a0, 0xc00014d400, 0xc0004f24b0, 0x17fd520, 0xc000134068, 0x509946)
	/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x9c
github.com/razorpay/metro/internal/interceptors.UnaryServerTagInterceptor.func1(0x18035a0, 0xc000448de0, 0x14bf7a0, 0xc00014d400, 0xc0005dd440, 0xc00014d450, 0xc000134068, 0x18035a0, 0xc000448de0, 0xc000134068)
	/src/internal/interceptors/tags.go:33 +0x1c8
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x18035a0, 0xc000448de0, 0x14bf7a0, 0xc00014d400, 0x20, 0xc000485ab0, 0x476478, 0x50)
	/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x9c
github.com/grpc-ecosystem/go-grpc-middleware/tags.UnaryServerInterceptor.func1(0x18035a0, 0xc000448d80, 0x14bf7a0, 0xc00014d400, 0xc0005dd440, 0xc00014d450, 0xc0000d86c0, 0x0, 0xc000485b30, 0x476478)
	/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/tags/interceptors.go:21 +0x89
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x18035a0, 0xc000448d80, 0x14bf7a0, 0xc00014d400, 0xc0005dd440, 0xc0005dd480, 0xc000373ba0, 0x509946, 0x14dfec0, 0xc000448d80)
	/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:39 +0x15b
github.com/razorpay/metro/rpc/proto/v1._Publisher_Publish_Handler(0x143d020, 0xc0000d4d20, 0x18035a0, 0xc000448d80, 0xc00055c3c0, 0xc0000d4bd0, 0x18035a0, 0xc000448d80, 0xc0003a6450, 0x26)
	/src/rpc/proto/v1/spec_grpc.pb.go:344 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000ec000, 0x180f580, 0xc000727800, 0xc0000d86c0, 0xc0000d4db0, 0x1f71738, 0x0, 0x0, 0x0)
	/src/vendor/google.golang.org/grpc/server.go:1217 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc0000ec000, 0x180f580, 0xc000727800, 0xc0000d86c0, 0x0)
	/src/vendor/google.golang.org/grpc/server.go:1540 +0xd05
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0002ba1d0, 0xc0000ec000, 0x180f580, 0xc000727800, 0xc0000d86c0)
	/src/vendor/google.golang.org/grpc/server.go:878 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/src/vendor/google.golang.org/grpc/server.go:876 +0x1fd
```

**Comment by sunnyagg** [comment]
Fixed with PR #118 

Consul registry returns null on key not found cases without error, added check on key null
